package org.kanban.userservice.domain.model;

import lombok.Builder;
import lombok.Getter;

import java.time.LocalDateTime;

@Getter
@Builder
public class User {
    private final UserId id;
    private Username username;
    private Email email;
    private PasswordHash passwordHash;
    private FullName fullName;
    private AvatarUrl avatarUrl;
    private final LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public static User createNew(Username username, Email email, PasswordHash passwordHash, FullName fullName, AvatarUrl avatarUrl) {
        return User.builder()
                .id(null) // ID will be generated by DB upon persistence
                .username(username)
                .email(email)
                .passwordHash(passwordHash)
                .fullName(fullName)
                .avatarUrl(avatarUrl)
                .createdAt(LocalDateTime.now())
                .updatedAt(LocalDateTime.now())
                .build();
    }

    public void updateProfile(FullName fullName, AvatarUrl avatarUrl) {
        this.fullName = fullName;
        this.avatarUrl = avatarUrl;
        this.updatedAt = LocalDateTime.now();
    }

    public void changeEmail(Email email) {
        this.email = email;
        this.updatedAt = LocalDateTime.now();
    }

    public void changePassword(PasswordHash passwordHash) {
        this.passwordHash = passwordHash;
        this.updatedAt = LocalDateTime.now();
    }
}
